version: '3.8'

volumes:
  postgres_volume:
  staticfiles_volume:
  mediafiles_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ayztuva/foodgram
    restart: always
    command: gunicorn foodgram.wsgi:application -b 0:8000
    depends_on: 
      - db
    env_file: ./.env
    volumes:
      - staticfiles_volume:/static
      - mediafiles_volume:/media

  nginx:
    image: nginx:1.19.6
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles_volume:/static
      - mediafiles_volume:/media