# Generated by Django 3.1.6 on 2021-03-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210313_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
